import Link from "next/link";

const steps = [["From marks to meaning", "Connect test data, topic patterns and student reflection so the story behind each score becomes visible."], ["Clarity before the conversation", "Help teachers enter every academic discussion with a clearer picture of where each learner stands and what matters most."], ["Action that earns trust", "Turn each insight into a practical starting point teachers can interrogate, adapt and build on with confidence."]];

export default function PilotPage() { return <>
  <section className="page-hero py-20 sm:py-28"><div className="container mx-auto grid gap-12 px-4 sm:px-6 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:px-8"><div><p className="eyebrow">Pilot programme</p><h1 className="section-title max-w-3xl">A pilot that fits into your workflow, not the other way around.</h1><p className="section-copy">Cavalaid brings assessment data and student reflection into one focused learning loop. The pilot is designed to show whether the intelligence layer fits your institute—not to add complexity to it.</p><Link href="/contact" className="mt-8 inline-flex rounded-lg bg-[#0b5f70] px-6 py-3.5 font-semibold text-white transition hover:bg-[#084a57]">Discuss a pilot</Link></div><div className="rounded-2xl bg-[#081b33] p-7 text-white shadow-xl shadow-cyan-950/10"><p className="text-sm font-semibold text-cyan-300">A focused pilot</p><ul className="mt-6 space-y-4 text-slate-200">{["One institute and one defined academic workflow", "Guided setup for test data and student reflection", "Regular reviews of insight quality and teacher use", "A documented learning loop for the next cycle"].map((item) => <li key={item} className="flex gap-3"><span className="text-cyan-300">✓</span>{item}</li>)}</ul></div></div></section>
  <section className="py-20 sm:py-28"><div className="container mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="eyebrow">A thoughtful rollout</p><h2 className="section-title">A pilot designed around momentum, not disruption.</h2></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{steps.map(([title, copy], i) => <article className="rounded-2xl border border-slate-200 bg-white p-7 shadow-sm" key={title}><p className="text-sm font-semibold text-[#0b7285]">0{i + 1}</p><h3 className="mt-7 text-xl font-semibold tracking-tight">{title}</h3><p className="mt-3 leading-7 text-slate-600">{copy}</p></article>)}</div></div></section>
  <section className="bg-[#e8f8fa] py-20 sm:py-28"><div className="container mx-auto grid gap-10 px-4 sm:px-6 lg:grid-cols-2 lg:gap-20 lg:px-8"><div><p className="eyebrow">What good looks like</p><h2 className="section-title">Evidence your academic team can use to decide what comes next.</h2><p className="section-copy">We agree on the success measures before the pilot begins. The focus is practical: can the data be used reliably, are the insights trusted, and do they help teachers act differently?</p></div><div className="space-y-3">{["Question-level results are imported and mapped to topics reliably.", "Students complete reflections that add useful context to the test data.", "Teachers can judge whether an insight is true from the evidence shown.", "The team can point to an action or workflow improvement informed by the cycle."].map((item) => <div key={item} className="rounded-xl border border-cyan-950/5 bg-white p-5 font-medium text-slate-700 shadow-sm"><span className="mr-3 text-[#0b7285]">✓</span>{item}</div>)}</div></div></section>
  </>; }
