"use client";

import { useState } from "react";

export default function ContactPage() {
  const [status, setStatus] = useState<"idle" | "sending" | "sent" | "error">("idle");
  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setStatus("sending"); const form = new FormData(event.currentTarget); try { const response = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }); setStatus(response.ok ? "sent" : "error"); } catch { setStatus("error"); } }
  return <section className="page-hero min-h-[calc(100vh-4rem)] py-16 sm:py-24"><div className="container mx-auto grid max-w-6xl gap-12 px-4 sm:px-6 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:px-8"><div><p className="eyebrow">Let’s begin with your reality</p><h1 className="section-title">Tell us what your academic team wants to see more clearly.</h1><p className="section-copy">Whether you are exploring a pilot or simply want a better view of your students’ learning journey, we would like to hear how your institute works today.</p><div className="mt-8 space-y-4">{[["A focused conversation", "We start with the workflow that matters most to your team."], ["No generic demo", "Your walkthrough is shaped around the questions you want to answer."], ["A practical next step", "Leave with a clearer sense of where Cavalaid could add value."]].map(([title, copy]) => <div key={title} className="flex gap-3"><span className="mt-1 text-[#0b7285]">✓</span><div><p className="font-semibold text-slate-800">{title}</p><p className="mt-1 text-sm leading-6 text-slate-600">{copy}</p></div></div>)}</div></div><div className="rounded-2xl border border-white bg-white p-7 shadow-xl shadow-cyan-950/10 sm:p-9">{status === "sent" ? <div className="py-12 text-center"><span className="grid mx-auto h-12 w-12 place-items-center rounded-full bg-[#e8f8fa] text-xl text-[#0b7285]">✓</span><h2 className="mt-6 text-2xl font-semibold tracking-tight text-slate-900">Thank you—we’ll be in touch.</h2><p className="mt-3 leading-7 text-slate-600">Your details are with our team. We will follow up to arrange a useful conversation.</p></div> : <form onSubmit={handleSubmit} className="space-y-5"><div><p className="text-lg font-semibold tracking-tight text-slate-900">Request a walkthrough</p><p className="mt-1 text-sm text-slate-500">A few details help us prepare well.</p></div><Field label="Institute name" name="institute" required /><Field label="Work email" name="email" type="email" required /><Field label="Approximate number of students" name="students" placeholder="For example, 350" /><div><label className="mb-1.5 block text-sm font-medium text-slate-700">Tell us about yourself</label><textarea name="message" rows={4} placeholder="Tell us a little about your current academic workflow." className="w-full rounded-lg border border-slate-300 px-4 py-3 text-slate-900 outline-none transition focus:border-[#0b7285] focus:ring-2 focus:ring-cyan-100" /></div>{status === "error" && <p className="text-sm text-red-600">We could not send that right now. Please try again shortly.</p>}<button disabled={status === "sending"} className="w-full rounded-lg bg-[#0b5f70] px-6 py-3.5 font-semibold text-white transition hover:bg-[#084a57] disabled:opacity-50">{status === "sending" ? "Sending…" : "Request a walkthrough"}</button></form>}</div></div></section>;
}

function Field({ label, name, type = "text", required = false, placeholder }: { label: string; name: string; type?: string; required?: boolean; placeholder?: string }) { return <div><label className="mb-1.5 block text-sm font-medium text-slate-700">{label}</label><input name={name} type={type} required={required} placeholder={placeholder} className="w-full rounded-lg border border-slate-300 px-4 py-3 text-slate-900 outline-none transition focus:border-[#0b7285] focus:ring-2 focus:ring-cyan-100" /></div>; }
